services:
  - type: web
    name: app3monkeys
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project3monkeys.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres3monkeys
          property: connectionString
databases:
  - name: postgres3monkeys
    plan: free
