# Generated by Django 5.2 on 2025-06-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
