# Generated by Django 5.2 on 2025-06-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
