# Generated by Django 5.2 on 2025-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
