# Generated by Django 5.2.2 on 2025-06-18 06:21

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0007_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='vendor',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='checklist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'WiFi'), ('pool', 'Pool'), ('parking', 'Parking'), ('pet_friendly', 'Pet Friendly')], max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='eminities',
            field=models.TextField(default='-', help_text='You can enter HTML content here.'),
        ),
        migrations.AddField(
            model_name='property',
            name='guest_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
