# Generated by Django 5.2.2 on 2025-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0008_remove_property_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='checklist',
            new_name='Aminities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='eminities',
        ),
        migrations.AlterField(
            model_name='property',
            name='guest_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
