# Generated by Django 5.2.2 on 2025-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0008_event_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image_url',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='event',
            name='guestLimit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
