# Generated by Django 5.2.2 on 2025-06-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0009_rename_checklist_property_aminities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='guest_limit',
            new_name='guest_Limit',
        ),
    ]
