# Generated by Django 5.2.2 on 2025-06-18 06:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0009_rename_category_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'WiFi'), ('pool', 'Pool'), ('parking', 'Parking'), ('pet', 'Pet Friendly')], max_length=21, null=True),
        ),
    ]
