# Generated by Django 5.2.2 on 2025-06-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0010_rename_guest_limit_property_guest_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Aminities',
            new_name='aminities',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='guest_Limit',
            new_name='guestLimit',
        ),
    ]
